/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alumno
 */
public class Conversor extends javax.swing.JFrame {
    
    Double CapturaDiv=0.0;
    Double Convercion=0.0;
    String Divisa1 = "GTQ";
    String Divisa2 = "GTQ";
    public Conversor() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DivisiaInicial = new javax.swing.JTextField();
        DivisaOrigen = new javax.swing.JComboBox<>();
        DivisaFinal = new javax.swing.JComboBox<>();
        RealizarConv = new javax.swing.JButton();
        MostrarRes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Divisas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Intruduce importe:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Convertir a:");

        DivisaOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        DivisaOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisaOrigenActionPerformed(evt);
            }
        });

        DivisaFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GTQ", "USD", "EUR", "PESO MX" }));
        DivisaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisaFinalActionPerformed(evt);
            }
        });

        RealizarConv.setText("Convertir");
        RealizarConv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarConvActionPerformed(evt);
            }
        });

        MostrarRes.setBackground(new java.awt.Color(255, 255, 255));
        MostrarRes.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DivisaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RealizarConv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(DivisiaInicial))
                        .addGap(41, 41, 41)
                        .addComponent(DivisaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MostrarRes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DivisiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DivisaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DivisaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RealizarConv))
                .addGap(18, 18, 18)
                .addComponent(MostrarRes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RealizarConvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarConvActionPerformed

        CapturaDiv = Double.parseDouble(DivisiaInicial.getText());
        convertidor();
        String DivisaSelc = "  ";
        DivisaSelc=DivisaSelc+DivisaFinal.getSelectedItem().toString();
        //Mostrar la convercion
        MostrarRes.setText("Resultado: "+Convercion +DivisaSelc);
        
    }//GEN-LAST:event_RealizarConvActionPerformed
    
    private void DivisaOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisaOrigenActionPerformed
        Divisa1=DivisaOrigen.getSelectedItem().toString();
        convertidor();
    }//GEN-LAST:event_DivisaOrigenActionPerformed

    private void DivisaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisaFinalActionPerformed
        Divisa2=DivisaFinal.getSelectedItem().toString();
        convertidor();
    }//GEN-LAST:event_DivisaFinalActionPerformed
public void convertidor(){

    switch(Divisa1)
    {
        case "GTQ":
        {
            if(Divisa2.equals("USD"))
            {
                Convercion = CapturaDiv*0.13;
            }
            else if (Divisa2.equals("EUR"))
            {
                Convercion = CapturaDiv*0.12;
            }
            else if (Divisa2.equals("PESO MX"))
            {
                Convercion = CapturaDiv*2.63;
            }
            else
            {
                Convercion = CapturaDiv;
            }
            break;
        }
        case "USD":
        {
            if(Divisa2.equals("GTQ"))
            {
                Convercion = CapturaDiv*7.67;
            }
            else if (Divisa2.equals("EUR"))
            {
                Convercion = CapturaDiv*0.95;
            }
            else if (Divisa2.equals("PESO MX"))
            {
                Convercion = CapturaDiv*20.18;
            }
            else
            {
                Convercion = CapturaDiv;
            }
            break;
        }
        case "EUR":
        {
            if(Divisa2.equals("USD"))
            {
                Convercion = CapturaDiv*1.05;
            }
            else if (Divisa2.equals("GTQ"))
            {
                Convercion = CapturaDiv*8.08;
            }
            else if (Divisa2.equals("PESO MX"))
            {
                Convercion = CapturaDiv*21.26;
            }
            else
            {
                Convercion = CapturaDiv;
            }
            break;
        }
        case "PESO MX":
        {
            if(Divisa2.equals("USD"))
            {
                Convercion = CapturaDiv*0.050;
            }
            else if (Divisa2.equals("GTQ"))
            {
                Convercion = CapturaDiv*0.38;
            }
            else if (Divisa2.equals("EUR"))
            {
                Convercion = CapturaDiv*0.047;
            }
            else
            {
                Convercion = CapturaDiv;
            }
            break;
        }
    }   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DivisaFinal;
    private javax.swing.JComboBox<String> DivisaOrigen;
    private javax.swing.JTextField DivisiaInicial;
    private javax.swing.JLabel MostrarRes;
    private javax.swing.JButton RealizarConv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
